#CUSTOMER INFORMATION SHEET
date = input("Please enter today's Date  ")
print()

name = input("please enter your Name  ")
print()
phone = input("please enter your phone  ")
print()
address = input("please enter your address  ")
print()
email = input("please enter email address  ")
print()
brand_name = input("Brand Name / Model Number  ")
print()
password = input("Password if any  ")
print()
List = input("List the items you are dropping off  ")
print()
problem = input("Please enter the problem you are having with your Laptop  ")
print()
running = input("Were  you running any particular software when this problem occured  ")
print()
add = input("did you add any new hardware when this problem occured  ")
print()
screen_damage = input("Is the LCD screen damaged? Yes/No   ")
print()
missing_keys = input("are there any missing keys? Yes/No  ")
print()
plastic_damage = input("Plastic damaged or scratched?  Yes/No  ")

print()
customer_signature = input("Please sign here  ")
print()
date_picked_up = input("Please enter the date you picked up.  ")
print()